- name: "Fetch certificate files"

  become: true

  vars_files:
    - "vars/cert_locations.yml"
    - "secrets/secrets.yml"

  vars:
    host: "rproxy"
    cert_data:
      - cert_domain: "wan.centennialchristian.ca"
        cert_remote_dir: "/opt/nginx-proxy-manager/data/custom_ssl/npm-1"
        cert_source: "letsencrypt"
    cert_remote: "{{ cert_remote_dir }}/fullchain.pem"
    new_certs: []

  hosts: "{{ host }}"

  handlers:
    - name: "archive existing certificate files"
      ansible.builtin.include_tasks:
        file: "tasks/archive-existing-cert-files_handlers.yml"

    - name: "fetch new certificate files"
      ansible.builtin.include_tasks:
        file: "tasks/get-new-cert-files_handlers.yml"

  tasks:
    - loop: "{{ cert_data }}"
      loop_control:
        loop_var: cert_values
      ansible.builtin.include_tasks:
        file: "tasks/cert-fetch_tasks.yml"
